# Generated by Django 5.2.8 on 2026-04-27 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('role', models.CharField(max_length=100, verbose_name='Должность')),
                ('salary', models.FloatField(verbose_name='Оклад')),
                ('status', models.CharField(default='Работает', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=1000000.0, verbose_name='Баланс предприятия')),
                ('income', models.FloatField(default=0.0, verbose_name='Общий доход')),
                ('expenses', models.FloatField(default=0.0, verbose_name='Общий расход')),
            ],
            options={
                'verbose_name': 'Финансы',
                'verbose_name_plural': 'Финансы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('price', models.FloatField(verbose_name='Цена продажи')),
                ('type', models.CharField(max_length=50, verbose_name='Тип продукта')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Сорт нефти')),
                ('density', models.FloatField(verbose_name='Плотность')),
                ('sulfur', models.FloatField(verbose_name='Содержание серы')),
                ('price', models.FloatField(verbose_name='Цена за тонну')),
                ('type', models.CharField(max_length=50, verbose_name='Тип (Легкая/Тяжелая)')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0, verbose_name='Количество')),
                ('capacity', models.FloatField(verbose_name='Вместимость')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Продукт')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField(verbose_name='Объем')),
                ('total_price', models.FloatField(verbose_name='Сумма')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.CharField(max_length=100, verbose_name='Поставщик')),
                ('oil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_used', models.FloatField(verbose_name='Объем сырья')),
                ('mode', models.CharField(max_length=100, verbose_name='Режим производства')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('oil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='RawStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.FloatField(verbose_name='Макс. объем')),
                ('current_volume', models.FloatField(default=0, verbose_name='Текущий объем')),
                ('oil_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.rawmaterial', verbose_name='Тип нефти')),
            ],
        ),
    ]
