# Generated by Django 5.2.8 on 2026-04-27 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='production',
            options={'verbose_name': 'Операция производства', 'verbose_name_plural': 'Операции производства'},
        ),
        migrations.AlterModelOptions(
            name='productstorage',
            options={'verbose_name': 'Склад продукции', 'verbose_name_plural': 'Склады продукции'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Закупка', 'verbose_name_plural': 'Закупки'},
        ),
        migrations.AlterModelOptions(
            name='rawmaterial',
            options={'verbose_name': 'Сорт нефти', 'verbose_name_plural': 'Сорта нефти'},
        ),
        migrations.AlterModelOptions(
            name='rawstorage',
            options={'verbose_name': 'Склад сырья', 'verbose_name_plural': 'Склады сырья'},
        ),
        migrations.RenameField(
            model_name='rawmaterial',
            old_name='price',
            new_name='price_per_ton',
        ),
        migrations.RenameField(
            model_name='rawstorage',
            old_name='oil_type',
            new_name='oil_material',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='type',
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='oil_type',
            field=models.CharField(choices=[('light', 'Легкая (малосернистая)'), ('medium', 'Средняя'), ('heavy', 'Тяжелая (высокосернистая)')], default='medium', max_length=20, verbose_name='Тип нефти'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='paraffin',
            field=models.FloatField(default=1.0, verbose_name='Парафины (%)'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='water_content',
            field=models.FloatField(default=0.1, verbose_name='Содержание воды (%)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('purchaser', 'Менеджер по закупкам'), ('technologist', 'Технолог'), ('sales', 'Менеджер по продажам'), ('accountant', 'Бухгалтер'), ('admin', 'Администратор')], max_length=20, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(default='Работает', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Цена продажи за тонну'),
        ),
        migrations.AlterField(
            model_name='production',
            name='mode',
            field=models.CharField(choices=[('gasoline', 'Упор на бензин'), ('diesel', 'Упор на дизель'), ('heavy', 'Упор на мазут/асфальт'), ('balanced', 'Сбалансированный')], max_length=20, verbose_name='Режим производства'),
        ),
        migrations.AlterField(
            model_name='production',
            name='oil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rawmaterial', verbose_name='Используемое сырье'),
        ),
        migrations.AlterField(
            model_name='production',
            name='volume_used',
            field=models.FloatField(verbose_name='Объем сырья (т)'),
        ),
        migrations.AlterField(
            model_name='productstorage',
            name='capacity',
            field=models.FloatField(verbose_name='Вместимость (т)'),
        ),
        migrations.AlterField(
            model_name='productstorage',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Количество (т)'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата закупки'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='oil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rawmaterial', verbose_name='Сорт нефти'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_price',
            field=models.FloatField(verbose_name='Итоговая сумма'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='volume',
            field=models.FloatField(verbose_name='Объем (т)'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='density',
            field=models.FloatField(verbose_name='Плотность (кг/м3)'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='sulfur',
            field=models.FloatField(verbose_name='Содержание серы (%)'),
        ),
        migrations.AlterField(
            model_name='rawstorage',
            name='capacity',
            field=models.FloatField(verbose_name='Макс. объем (т)'),
        ),
        migrations.AlterField(
            model_name='rawstorage',
            name='current_volume',
            field=models.FloatField(default=0, verbose_name='Текущий объем (т)'),
        ),
    ]
