# Generated by Django 5.2.8 on 2026-04-27 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_employee_options_alter_production_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='production',
            name='additives',
            field=models.FloatField(default=0, verbose_name='Присадки (т)'),
        ),
        migrations.CreateModel(
            name='ProductionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasoline', models.FloatField(default=0, verbose_name='Бензин (т)')),
                ('diesel', models.FloatField(default=0, verbose_name='Дизель (т)')),
                ('kerosene', models.FloatField(default=0, verbose_name='Керосин (т)')),
                ('mazut', models.FloatField(default=0, verbose_name='Мазут (т)')),
                ('asphalt', models.FloatField(default=0, verbose_name='Асфальт (т)')),
                ('losses', models.FloatField(default=0, verbose_name='Потери (т)')),
                ('production', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='core.production')),
            ],
            options={
                'verbose_name': 'Результат переработки',
                'verbose_name_plural': 'Результаты переработки',
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Сумма выплаты')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Выплата зарплаты',
                'verbose_name_plural': 'Выплаты зарплаты',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Количество (т)')),
                ('total_price', models.FloatField(verbose_name='Сумма сделки')),
                ('client', models.CharField(max_length=255, verbose_name='Покупатель')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
    ]
