# Generated by Django 6.0.4 on 2026-05-11 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_options_production_additives_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price_retail',
            field=models.FloatField(default=0.0, verbose_name='Розница (цена за т)'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_wholesale',
            field=models.FloatField(default=0.0, verbose_name='Опт (цена за т)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('retail', 'Розница'), ('wholesale', 'Опт')], default='retail', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_rate',
            field=models.FloatField(default=12.0, verbose_name='НДС (%)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.FloatField(verbose_name='Сумма сделки (с налогом)'),
        ),
    ]
