# Generated by Django 6.0.4 on 2026-05-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_options_alter_sale_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstorage',
            name='capacity',
            field=models.FloatField(default=5000.0, verbose_name='Вместимость (т)'),
        ),
    ]
