# Generated by Django 6.0.4 on 2026-05-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_productstorage_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.FloatField(verbose_name='Оклад (USD)'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='balance',
            field=models.FloatField(default=1000000.0, verbose_name='Баланс предприятия (USD)'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='expenses',
            field=models.FloatField(default=0.0, verbose_name='Общий расход (USD)'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='income',
            field=models.FloatField(default=0.0, verbose_name='Общий доход (USD)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_retail',
            field=models.FloatField(default=0.0, verbose_name='Розница (USD за т)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_wholesale',
            field=models.FloatField(default=0.0, verbose_name='Опт (USD за т)'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_price',
            field=models.FloatField(verbose_name='Итоговая сумма (USD)'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='price_per_ton',
            field=models.FloatField(verbose_name='Цена за тонну (USD)'),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='amount',
            field=models.FloatField(verbose_name='Сумма выплаты (USD)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.FloatField(verbose_name='Сумма сделки с налогом (USD)'),
        ),
    ]
