# Generated by Django 6.0.4 on 2026-05-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_employee_salary_alter_finance_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='production_cost',
            field=models.FloatField(default=0.0, verbose_name='Себестоимость (USD за т)'),
        ),
    ]
