# Generated by Django 6.0.4 on 2026-05-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_production_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Заказчик (например, Газпром нефть)')),
                ('product_name', models.CharField(max_length=100, verbose_name='Требуемый продукт')),
                ('required_quantity', models.FloatField(verbose_name='Необходимый объем (т)')),
                ('reward_price', models.FloatField(verbose_name='Цена контракта ($)')),
                ('deadline', models.DateTimeField(verbose_name='Срок выполнения')),
                ('status', models.CharField(choices=[('open', 'Открыт (Тендер)'), ('in_progress', 'Выполняется'), ('completed', 'Завершен'), ('failed', 'Провален')], default='open', max_length=20)),
            ],
        ),
    ]
