# Generated by Django 6.0.4 on 2026-05-18 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Тендер / Контракт', 'verbose_name_plural': 'Биржа тендеров'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Требуемый продукт'),
            preserve_default=False,
        ),
    ]
