# Generated by Django 6.0.4 on 2026-05-21 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_product_options_alter_sale_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
